from __future__ import annotations

from pathlib import Path

from .. import ENGINE_VERSION
from ..contracts import read_json, write_json
from ..paths import output_dir, plan_dir
from ..producers.final_renderer import render_final, validate_final_outputs
from ..reporting.provenance import provenance_fields
from ..stage_result import FINAL_BLOCKED, PASS, StageResult, current_command, failure
from .common import all_previous_pass


PREVIOUS = ["S0_intake", "S1_script_and_subtitles", "S1_5_subtitle_layout_planning", "S2_visual_plan", "S3_asset_sourcing", "S4_base_timeline", "S5_motion_overlay", "S6_text_layout", "S7_process_validation"]


def run(project_dir: Path, allow_fixtures: bool = False, **_: object) -> StageResult:
    del allow_fixtures
    failures = []
    if not all_previous_pass(project_dir, PREVIOUS):
        failures.append(failure("previous_stages_not_passed", "S0-S7 are not all PASS.", "Fix blocked stages before final render."))
    renderer_outputs: list[Path] = []
    if not failures:
        renderer_outputs, render_failures = render_final(project_dir)
        failures.extend(render_failures)
    else:
        failures.extend(validate_final_outputs(project_dir))
    final_mp4 = output_dir(project_dir) / "final.mp4"
    final_report_path = plan_dir(project_dir) / "final_validation_report.json"
    acceptance_path = plan_dir(project_dir) / "production_acceptance_report.json"
    metadata_path = plan_dir(project_dir) / "final_video_metadata.json"
    render_log_path = plan_dir(project_dir) / "final_render_log.json"
    status = FINAL_BLOCKED if failures else PASS
    final_inputs = [
        plan_dir(project_dir) / "final_render_log.json",
        plan_dir(project_dir) / "final_video_metadata.json",
        plan_dir(project_dir) / "final_stream_probe.json",
        final_mp4,
    ]
    stage_reports = [plan_dir(project_dir) / "stage_reports" / f"{stage}.json" for stage in PREVIOUS]
    final_outputs = [final_mp4] if final_mp4.exists() else []
    final_common = {**provenance_fields("final_validation", final_inputs, final_outputs), "validator": "s8_final_render_and_validation"}
    acceptance_common = {**provenance_fields("production_acceptance", [*stage_reports, *final_inputs], final_outputs), "validator": "validate_production"}
    write_json(final_report_path, {**final_common, "status": status, "can_claim_complete": not failures, "failure_codes": [item["code"] for item in failures], "failures": failures})
    write_json(acceptance_path, {**acceptance_common, "status": status, "can_claim_complete": not failures, "failure_codes": [item["code"] for item in failures], "failures": failures})
    if not failures:
        (output_dir(project_dir) / "FINAL_REPORT.md").write_text("Generated by short_video_engine after production acceptance PASS.\n", encoding="utf-8")
    else:
        stale_report = output_dir(project_dir) / "FINAL_REPORT.md"
        if stale_report.exists():
            stale_report.unlink()
    outputs = [metadata_path, render_log_path, final_mp4, *renderer_outputs]
    return StageResult("S8_final_render_and_validation", status, "s8_final_render_and_validation", current_command(), failures=failures, outputs=outputs, can_claim_complete=not failures)
