from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

from ..contracts import read_json
from ..paths import plan_dir
from ..stage_result import failure
from ..producers.motion_icon_resolver import sanitize_svg


def validate_motion_icons(project_dir: Path, *, require_layers: bool = True) -> list[dict[str, str]]:
    manifest_path = plan_dir(project_dir) / "motion_icon_manifest.json"
    manifest = read_json(manifest_path, {})
    failures: list[dict[str, str]] = []
    if manifest.get("generated_by") != "short_video_engine":
        return [failure("motion_icon_manifest_missing", "motion_icon_manifest.json must be generated by S4.5.")]
    icons = manifest.get("icons") if isinstance(manifest.get("icons"), list) else []
    icon_ids: set[str] = set()
    hashes: dict[str, str] = {}
    for icon in icons:
        if not isinstance(icon, dict):
            continue
        icon_ids.add(str(icon.get("icon_id") or ""))
        local = Path(str(icon.get("local_path") or "")); public = project_dir / "work" / "remotion_public" / str(icon.get("public_path") or "")
        public_path = str(icon.get("public_path") or "")
        if icon.get("source_type") not in {"generated_svg", "bundled_svg", "downloaded_svg"}:
            failures.append(failure("invalid_motion_icon_source_type", "Motion icon source type must be SVG-only."))
        if not public_path or Path(public_path).is_absolute() or ".." in Path(public_path).parts:
            failures.append(failure("motion_icon_public_path_invalid", "Motion icon public_path must be relative."))
        if not local.exists() or local.suffix.lower() != ".svg" or not public.exists():
            failures.append(failure("motion_icon_file_missing", f"Missing localized SVG icon {icon.get('icon_id')}.")); continue
        content = local.read_text(encoding="utf-8", errors="ignore")
        if not sanitize_svg(content):
            failures.append(failure("motion_icon_svg_sanitization_failed", f"Unsafe SVG {icon.get('icon_id')}."))
        digest = hashlib.sha256(local.read_bytes()).hexdigest()
        if digest != icon.get("sha256"):
            failures.append(failure("motion_icon_hash_mismatch", f"Hash mismatch for {icon.get('icon_id')}."))
        hashes[str(icon.get("semantic_key") or "")] = digest
        if icon.get("sanitization_status") != "passed":
            failures.append(failure("motion_icon_not_sanitized", f"SVG {icon.get('icon_id')} was not sanitized."))
        if icon.get("source_type") == "downloaded_svg" and (not icon.get("license_or_note") or not icon.get("source_url")):
            failures.append(failure("downloaded_motion_icon_missing_provenance", "Downloaded SVG requires source URL and license provenance."))
    key_hashes = [hashes[key] for key in ("chip", "connector", "server", "warning", "database") if key in hashes]
    if len(key_hashes) >= 3 and len(set(key_hashes)) == 1:
        failures.append(failure("motion_icon_semantics_collapsed", "Distinct key semantics cannot all use one SVG hash."))
    if require_layers:
        layers = read_json(plan_dir(project_dir) / "motion_layers.json", {}).get("layers") or []
        for layer in layers if isinstance(layers, list) else []:
            if isinstance(layer, dict):
                unknown = set(layer.get("used_icon_ids") or []) - icon_ids
                if unknown:
                    failures.append(failure("motion_layer_unknown_icon_id", "Motion layer references an icon outside the manifest."))
    return failures
